-- SafeIn5 sample-documents job-pack seed
-- Source: docs/sample documents/
-- Regenerated by: node scripts/generate-sample-job-pack.mjs
--
-- Photographed Tarmac / Dolyhir pack for Hot Aggregate Bins (permit 098001).
-- Inserts draft/unpublished rows. Safe to re-run.
--
--   psql -U postgres -d safein5 -v ON_ERROR_STOP=1 \
--     -f db/seed/sample-job-pack.sql

BEGIN;

DO $seed$
DECLARE
    v_tenant_id   integer;
    v_site_id     integer;
    v_space_id    integer;
    v_task_id     integer;
    v_pack_id     integer;
    v_byrne_id    integer;
    v_marshall_id integer;
    v_abrahams_id integer;
    v_hamnett_id  integer;
    v_whittle_id  integer;
    v_hira_id     integer;
    v_ptw_id      integer;
    v_rescue_id   integer;
    v_imsf_id     integer;
    v_clearance_id integer;
BEGIN

    SELECT id INTO v_tenant_id
    FROM tenant
    WHERE name = 'Tarmac' AND kind = 'corporate'
    ORDER BY id
    LIMIT 1;

    IF v_tenant_id IS NULL THEN
        INSERT INTO tenant (name, kind)
        VALUES ('Tarmac', 'corporate')
        RETURNING id INTO v_tenant_id;
    END IF;

    SELECT id INTO v_site_id
    FROM site
    WHERE tenant_id = v_tenant_id AND name = 'Dolyhir'
    ORDER BY id LIMIT 1;

    IF v_site_id IS NULL THEN
        INSERT INTO site (tenant_id, name)
        VALUES (v_tenant_id, 'Dolyhir')
        RETURNING id INTO v_site_id;
    END IF;

    INSERT INTO app_user (email, first_name, last_name, account_status)
    VALUES ('ja.byrne@seed.safein5.local', 'JA', 'Byrne', 'invited')
    ON CONFLICT (email) DO UPDATE
        SET first_name = EXCLUDED.first_name,
            last_name = EXCLUDED.last_name
    RETURNING id INTO v_byrne_id;

    INSERT INTO user_tenant_membership (user_id, tenant_id, role)
    VALUES (v_byrne_id, v_tenant_id, 'member')
    ON CONFLICT (user_id, tenant_id) DO UPDATE SET role = EXCLUDED.role;

    INSERT INTO user_site_membership (user_id, site_id, role_id)
    SELECT v_byrne_id, v_site_id, r.id FROM role r WHERE r.scope = 'site' AND r.key = 'site_manager'
    ON CONFLICT (user_id, site_id) DO UPDATE SET role_id = EXCLUDED.role_id;

    INSERT INTO app_user (email, first_name, last_name, account_status)
    VALUES ('jake.marshall@seed.safein5.local', 'Jake', 'Marshall', 'invited')
    ON CONFLICT (email) DO UPDATE
        SET first_name = EXCLUDED.first_name,
            last_name = EXCLUDED.last_name
    RETURNING id INTO v_marshall_id;

    INSERT INTO user_tenant_membership (user_id, tenant_id, role)
    VALUES (v_marshall_id, v_tenant_id, 'member')
    ON CONFLICT (user_id, tenant_id) DO UPDATE SET role = EXCLUDED.role;

    INSERT INTO user_site_membership (user_id, site_id, role_id)
    SELECT v_marshall_id, v_site_id, r.id FROM role r WHERE r.scope = 'site' AND r.key = 'supervisor'
    ON CONFLICT (user_id, site_id) DO UPDATE SET role_id = EXCLUDED.role_id;

    INSERT INTO app_user (email, first_name, last_name, account_status)
    VALUES ('j.abrahams@seed.safein5.local', 'J', 'Abrahams', 'invited')
    ON CONFLICT (email) DO UPDATE
        SET first_name = EXCLUDED.first_name,
            last_name = EXCLUDED.last_name
    RETURNING id INTO v_abrahams_id;

    INSERT INTO user_tenant_membership (user_id, tenant_id, role)
    VALUES (v_abrahams_id, v_tenant_id, 'member')
    ON CONFLICT (user_id, tenant_id) DO UPDATE SET role = EXCLUDED.role;

    INSERT INTO user_site_membership (user_id, site_id, role_id)
    SELECT v_abrahams_id, v_site_id, r.id FROM role r WHERE r.scope = 'site' AND r.key = 'supervisor'
    ON CONFLICT (user_id, site_id) DO UPDATE SET role_id = EXCLUDED.role_id;

    INSERT INTO app_user (email, first_name, last_name, account_status)
    VALUES ('t.hamnett@seed.safein5.local', 'T', 'Hamnett', 'invited')
    ON CONFLICT (email) DO UPDATE
        SET first_name = EXCLUDED.first_name,
            last_name = EXCLUDED.last_name
    RETURNING id INTO v_hamnett_id;

    INSERT INTO user_tenant_membership (user_id, tenant_id, role)
    VALUES (v_hamnett_id, v_tenant_id, 'member')
    ON CONFLICT (user_id, tenant_id) DO UPDATE SET role = EXCLUDED.role;

    INSERT INTO user_site_membership (user_id, site_id, role_id)
    SELECT v_hamnett_id, v_site_id, r.id FROM role r WHERE r.scope = 'site' AND r.key = 'worker'
    ON CONFLICT (user_id, site_id) DO UPDATE SET role_id = EXCLUDED.role_id;

    INSERT INTO app_user (email, first_name, last_name, account_status)
    VALUES ('nathan.whittle@seed.safein5.local', 'Nathan', 'Whittle', 'invited')
    ON CONFLICT (email) DO UPDATE
        SET first_name = EXCLUDED.first_name,
            last_name = EXCLUDED.last_name
    RETURNING id INTO v_whittle_id;

    INSERT INTO user_tenant_membership (user_id, tenant_id, role)
    VALUES (v_whittle_id, v_tenant_id, 'member')
    ON CONFLICT (user_id, tenant_id) DO UPDATE SET role = EXCLUDED.role;

    INSERT INTO user_site_membership (user_id, site_id, role_id)
    SELECT v_whittle_id, v_site_id, r.id FROM role r WHERE r.scope = 'site' AND r.key = 'worker'
    ON CONFLICT (user_id, site_id) DO UPDATE SET role_id = EXCLUDED.role_id;

    SELECT id INTO v_space_id
    FROM space
    WHERE tenant_id = v_tenant_id
      AND site_id = v_site_id
      AND name = 'Hot Aggregate Bins'
    ORDER BY id LIMIT 1;

    IF v_space_id IS NULL THEN
        INSERT INTO space (
            tenant_id, site_id, name, location, asset_type, task_type,
            permit_required, rescue_plan_required, owner_rule
        )
        VALUES (
            v_tenant_id, v_site_id, 'Hot Aggregate Bins',
            'Asphalt Plant, mixer house level 3',
            'Hot aggregate bins / confined space',
            'Confined space entry',
            true, true, 'Supervisor, Dolyhir'
        )
        RETURNING id INTO v_space_id;
    ELSE
        UPDATE space SET
            location = COALESCE(location, 'Asphalt Plant, mixer house level 3'),
            asset_type = COALESCE(asset_type, 'Hot aggregate bins / confined space'),
            task_type = COALESCE(task_type, 'Confined space entry'),
            permit_required = true,
            rescue_plan_required = true,
            owner_rule = COALESCE(owner_rule, 'Supervisor, Dolyhir')
        WHERE id = v_space_id;
    END IF;

    SELECT id INTO v_hira_id
    FROM document
    WHERE tenant_id = v_tenant_id AND title = 'Hazard Identification & Risk Assessment — Hot Bins / Chutes'
    ORDER BY id LIMIT 1;

    IF v_hira_id IS NULL THEN
        INSERT INTO document (tenant_id, title, doc_type, status)
        VALUES (v_tenant_id, 'Hazard Identification & Risk Assessment — Hot Bins / Chutes', 'risk_assessment', 'draft')
        RETURNING id INTO v_hira_id;

        INSERT INTO document_revision (
            document_id, revision, s3_key, mime_type, is_current
        )
        VALUES (
            v_hira_id, 'v1',
            'seed/sample-documents/RAMS/HIRA-Front-Page-1.jpeg', 'image/jpeg', true
        );
    END IF;

    SELECT id INTO v_ptw_id
    FROM document
    WHERE tenant_id = v_tenant_id AND title = 'Permit to Work 098001'
    ORDER BY id LIMIT 1;

    IF v_ptw_id IS NULL THEN
        INSERT INTO document (tenant_id, title, doc_type, status)
        VALUES (v_tenant_id, 'Permit to Work 098001', 'permit_to_work', 'draft')
        RETURNING id INTO v_ptw_id;

        INSERT INTO document_revision (
            document_id, revision, s3_key, mime_type, is_current
        )
        VALUES (
            v_ptw_id, 'v1',
            'seed/sample-documents/Permit-To-Work/Permit-to-Work-Front-Page.jpeg', 'image/jpeg', true
        );
    END IF;

    SELECT id INTO v_rescue_id
    FROM document
    WHERE tenant_id = v_tenant_id AND title = 'Confined Space Rescue Plan — Hot Aggregate Bins'
    ORDER BY id LIMIT 1;

    IF v_rescue_id IS NULL THEN
        INSERT INTO document (tenant_id, title, doc_type, status)
        VALUES (v_tenant_id, 'Confined Space Rescue Plan — Hot Aggregate Bins', 'rescue_plan', 'draft')
        RETURNING id INTO v_rescue_id;

        INSERT INTO document_revision (
            document_id, revision, s3_key, mime_type, is_current
        )
        VALUES (
            v_rescue_id, 'v1',
            'seed/sample-documents/Rescue-Plan/Rescue-Plan-Front-Page.jpeg', 'image/jpeg', true
        );
    END IF;

    SELECT id INTO v_imsf_id
    FROM document
    WHERE tenant_id = v_tenant_id AND title = 'IMSF 100 — Confined Spaces Checklist'
    ORDER BY id LIMIT 1;

    IF v_imsf_id IS NULL THEN
        INSERT INTO document (tenant_id, title, doc_type, status)
        VALUES (v_tenant_id, 'IMSF 100 — Confined Spaces Checklist', 'checklist', 'draft')
        RETURNING id INTO v_imsf_id;

        INSERT INTO document_revision (
            document_id, revision, s3_key, mime_type, is_current
        )
        VALUES (
            v_imsf_id, 'v1',
            'seed/sample-documents/Confined-Space-Check-List/CS-Check-List-Page-1.jpeg', 'image/jpeg', true
        );
    END IF;

    SELECT id INTO v_clearance_id
    FROM document
    WHERE tenant_id = v_tenant_id AND title = 'Contractors Clearance To Work Authorisation'
    ORDER BY id LIMIT 1;

    IF v_clearance_id IS NULL THEN
        INSERT INTO document (tenant_id, title, doc_type, status)
        VALUES (v_tenant_id, 'Contractors Clearance To Work Authorisation', 'other', 'draft')
        RETURNING id INTO v_clearance_id;

        INSERT INTO document_revision (
            document_id, revision, s3_key, mime_type, is_current
        )
        VALUES (
            v_clearance_id, 'v1',
            'seed/sample-documents/Contractor-Approval/Contractor-Clearance-main-page.jpeg', 'image/jpeg', true
        );
    END IF;

    SELECT id INTO v_task_id
    FROM work_task
    WHERE tenant_id = v_tenant_id AND reference = '098001'
    ORDER BY id LIMIT 1;

    IF v_task_id IS NULL THEN
        INSERT INTO work_task (
            tenant_id, site_id, space_id, reference, work_description, status,
            permit_required, permit_type, permit_number, permit_valid_until,
            rams_document_id, rams_reference, lead_user_id,
            starts_at, ends_at, planned_days
        )
        VALUES (
            v_tenant_id, v_site_id, v_space_id, '098001',
            'Repairs in Asphalt Plant Hot Agg Bins', 'active',
            true, 'Confined Space; Hot Work', '098001',
            timestamptz '2026-06-14 15:30:00+01',
            v_hira_id, 'HOTBINSRA01', v_marshall_id,
            timestamptz '2026-06-13 06:00:00+01',
            timestamptz '2026-06-14 15:30:00+01',
            2
        )
        RETURNING id INTO v_task_id;
    END IF;

    INSERT INTO work_task_crew (work_task_id, user_id)
    VALUES (v_task_id, v_hamnett_id), (v_task_id, v_whittle_id)
    ON CONFLICT (work_task_id, user_id) DO NOTHING;

    -- Placements: HIRA, PTW, contractor auth → task; rescue plan + IMSF 100 → space
    IF NOT EXISTS (
        SELECT 1 FROM document_placement
        WHERE document_id = v_hira_id AND work_task_id = v_task_id
    ) THEN
        INSERT INTO document_placement (document_id, scope_kind, work_task_id)
        VALUES (v_hira_id, 'work_task', v_task_id);
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM document_placement
        WHERE document_id = v_ptw_id AND work_task_id = v_task_id
    ) THEN
        INSERT INTO document_placement (document_id, scope_kind, work_task_id)
        VALUES (v_ptw_id, 'work_task', v_task_id);
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM document_placement
        WHERE document_id = v_clearance_id AND work_task_id = v_task_id
    ) THEN
        INSERT INTO document_placement (document_id, scope_kind, work_task_id)
        VALUES (v_clearance_id, 'work_task', v_task_id);
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM document_placement
        WHERE document_id = v_rescue_id AND space_id = v_space_id
    ) THEN
        INSERT INTO document_placement (document_id, scope_kind, space_id)
        VALUES (v_rescue_id, 'space', v_space_id);
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM document_placement
        WHERE document_id = v_imsf_id AND space_id = v_space_id
    ) THEN
        INSERT INTO document_placement (document_id, scope_kind, space_id)
        VALUES (v_imsf_id, 'space', v_space_id);
    END IF;

    SELECT id INTO v_pack_id
    FROM content_pack
    WHERE tenant_id = v_tenant_id
      AND kind = 'job_checklist'
      AND title = 'IMSF 100 — Confined Spaces Checklist'
    ORDER BY id LIMIT 1;

    IF v_pack_id IS NULL THEN
        INSERT INTO content_pack (
            tenant_id, kind, title, category, status, revision
        )
        VALUES (
            v_tenant_id, 'job_checklist',
            'IMSF 100 — Confined Spaces Checklist',
            'Confined space', 'draft',
            'v1'
        )
        RETURNING id INTO v_pack_id;
    END IF;

    DELETE FROM content_prompt WHERE content_pack_id = v_pack_id;
    INSERT INTO content_prompt (
        content_pack_id, sort_order, body_text, is_critical, is_mandatory
    )
    SELECT v_pack_id, x.sort_order, x.body_text, x.is_critical, x.is_mandatory
    FROM (VALUES
        ( 1, 'Can the need to enter the confined space be avoided?', true, true),
        ( 2, 'Can the confined space be permanently re-classified by removing the enclosed nature?', false, true),
        ( 3, 'Can the confined space be permanently re-classified by removing the specified hazard(s)?', false, true),
        ( 4, 'Can the confined space be temporarily re-classified by forced ventilation?', false, true),
        ( 5, 'If forced ventilation fails, is there sufficient time for a safe evacuation?', true, true),
        ( 6, 'Has a specific risk assessment been completed for the confined space?', true, true),
        ( 7, 'Has the risk assessment considered all conditions of operation, including abnormal and temporary conditions?', true, true),
        ( 8, 'Has the risk assessment considered the risks created by the planned work?', true, true),
        ( 9, 'Has a specific safe working procedure / safe system of work been prepared?', true, true),
        (10, 'Does the safe working procedure specify measures to take in an emergency?', true, true),
        (11, 'Has a Confined Space Permit been raised, including control measures from this checklist?', true, true),
        (12, 'Has a suitable warning sign been posted to identify the confined space?', false, true),
        (13, 'Has the confined space been secured to deter unauthorised access?', true, true),
        (14, 'Have fixed gas detectors or low oxygen monitors been provided in a suitable location?', true, true),
        (15, 'Are gas detectors adequately maintained and calibrated?', true, true),
        (16, 'Can the confined space be ventilated naturally to reduce unsafe atmosphere risk?', true, true),
        (17, 'Have fixed ventilation provisions been made?', false, true),
        (18, 'Is fixed ventilation maintained and tested periodically?', false, true),
        (19, 'Have cameras been fitted so persons inside the confined space can be monitored?', false, true),
        (20, 'Is there an adequate means of communication between persons inside and those outside?', true, true),
        (21, 'Is sufficient ventilation available?', true, true),
        (22, 'Is the level of lighting inside the confined space adequate?', false, true),
        (23, 'Can ambient temperature be controlled or monitored to prevent excessive heat?', true, true),
        (24, 'Has adequate access been provided for safe entry into the confined space?', true, true),
        (25, 'Are walkways and access platforms to the opening safe to use?', true, true),
        (26, 'Is access large enough for people wearing PPE including emergency breathing apparatus?', true, true),
        (27, 'Is sufficient access equipment available (tripod, full body harness and winch)?', true, true),
        (28, 'Have all persons who manage or enter the confined space received specific training and been authorised?', true, true),
        (29, 'Where the layout or task has physical constraints, are individuals of suitable build and fitness?', true, true),
        (30, 'Has the site appointed sufficient competent persons to issue a permit and supervise the activity?', true, true),
        (31, 'Are employees and contractors aware that a Permit to Work must be issued before entry?', true, true),
        (32, 'Are employees and contractors aware of procedures when the task, environment or method changes?', true, true),
        (33, 'Has the confined space been emptied of its contents, including residues where possible?', true, true),
        (34, 'Has the inside of the confined space been cleaned?', true, true),
        (35, 'Can pipework be isolated to prevent gas, fume or vapour entering?', true, true),
        (36, 'Can mechanical and electrical isolation prevent plant operating or discharging into the space?', true, true),
        (37, 'Are all isolations checked before work commences as part of the Permit to Work?', true, true),
        (38, 'Has the atmosphere been verified as safe prior to entry?', true, true),
        (39, 'Are signs displayed notifying that work is being undertaken and that people are inside?', true, true),
        (40, 'Where flammable or explosive atmospheres are possible, are ignition sources controlled?', true, true),
        (41, 'If appropriate, have non-sparking tools been specified and provided?', false, true),
        (42, 'Are suitable precautions in place to prevent electric shock inside metal tanks?', true, true),
        (43, 'Have calibrated personal air monitoring devices been provided for all persons who will enter?', true, true),
        (44, 'Have monitors and ELSA been checked prior to entry where required?', true, true),
        (45, 'Has the correct type of PPE been specified for each activity, including rescue equipment?', true, true),
        (46, 'Has suitable PPE been provided for all persons entering, and is it being used?', true, true),
        (47, 'Is PPE in good condition and appropriate for the conditions and activities?', false, true),
        (48, 'Has an emergency plan been prepared for this specific confined space?', true, true),
        (49, 'Has the site identified suitable emergency arrangements before work commences?', true, true),
        (50, 'Has a rescue procedure been defined and communicated?', true, true),
        (51, 'Is there a suitable method of raising the alarm?', true, true),
        (52, 'Has the response time of emergency services been considered?', true, true),
        (53, 'Has necessary rescue and resuscitation equipment been identified and provided?', true, true),
        (54, 'Are first aid provisions adequate?', true, true),
        (55, 'Are persons responsible for emergency response adequately trained and practised?', true, true),
        (56, 'If breathing apparatus is required, is the access a minimum of 575 mm square?', true, true)
    ) AS x(sort_order, body_text, is_critical, is_mandatory);

    IF NOT EXISTS (
        SELECT 1 FROM content_placement
        WHERE content_pack_id = v_pack_id
          AND scope_kind = 'space' AND space_id = v_space_id
    ) THEN
        INSERT INTO content_placement (content_pack_id, scope_kind, space_id)
        VALUES (v_pack_id, 'space', v_space_id);
    END IF;
END
$seed$;

COMMIT;

SELECT t.name AS tenant, s.name AS site, sp.name AS space,
       wt.reference, wt.work_description, wt.status
FROM work_task wt
JOIN tenant t ON t.id = wt.tenant_id
JOIN site s ON s.id = wt.site_id
JOIN space sp ON sp.id = wt.space_id
WHERE t.name = 'Tarmac' AND wt.reference = '098001';
